version: 2

sources:
  - name: raw_data
    schema: SF_SCHEMA
    database: SNOWFLAKE_DBT_DATA
    tables:
      - name: CUST         # logical name used in dbt model: {{ source('raw_data', 'CUST') }}
        identifier: CUSTOMER  # actual table name in Snowflake